# Opening GitHub Issues by Selecting Text

This bookdown document is a proof-of-concept for opening GitHub issues from a  [Medium-like](https://medium.com/) selection of text on a page.

The envisioned use case is a reader spots a typo. They select the text.
A popup opens with a button to click to open a GitHub issue. If they click on it, then they are taken to a new page to open GitHub issus. The issue's message is pre-filled with the text that they selected and a link to the page on which they found it.

The [share-this](https://github.com/MaxArt2501/share-this) provides the ability to share selections of text from a page.
I extended it by writing a new GitHub sharer.
This also depends on [FontAwesome](https://fontawesome.com/) for the GitHub icon.

The GitHub sharer needs to be configured with the GitHub repository associated with the site.
```{r echo=FALSE}
cat(readLines("share-this-config.js"))
```

The necessary files for this are:

-   `assets/share-this/*`: distribution files copied from 
-   `assets/share-this-github/*`: Javascript and CSS assets for the GitHub sharer
-   `includes/share-this.html`: A snippet of HTML included in each HTML page by bookdown. Some lines could be uncommented to load other sharers.

Add this line
```
bookdown::gitbook:
  css: style.css
  config:
    toc:
      before: |
        <li><a href="./">A Minimal Book Example</a></li>
      after: |
        <li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>
    edit: https://github.com/rstudio/bookdown-demo/edit/master/%s
    download: no
  lib_dir: "libs"
  self_contained: false
  includes:
    in_header: "includes/share-this.html"

```
