--- 
title: "A Minimal Example of Opening GitHub Issues with Selecting Text"
author: "Jeffrey Arnold"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
github-repo: jrnold/bookdown-github-issues
description: "This is a minimal example of using JavaScript to open issues with selected text from a webpage."
---

# Opening GitHub Issues by Selecting Text {-}

This bookdown document is a proof-of-concept for opening GitHub issues from a  [Medium-like](https://medium.com/) selection of text on a page.

The envisioned use case is a reader spots a typo. They select the text.
A popup opens with a button to click to open a GitHub issue. If they click on it, then they are taken to a new page to open GitHub issus. The issue's message is pre-filled with the text that they selected and a link to the page on which they found it.

The [share-this](https://github.com/MaxArt2501/share-this) provides the ability to share selections of text from a page.
I extended it by writing a new GitHub sharer.
This also depends on [FontAwesome](https://fontawesome.com/) for the GitHub icon.

## Setup {-}

Right now this is a proof of concept, so the only method is manually copying what is done in this repository.
Copy these files into your bookdown repository:

-   `assets/share-this/*`: distribution files copied from the share-this Javascript package.
-   `assets/share-this-github/*`: JavaScript and CSS assets for the GitHub sharer
-   `includes/share-this.html`: A snippet of HTML included in each HTML page by bookdown. Some lines could be uncommented to load other sharers.

Configuration and initialization is handled by the `share-this-config.js` file.
It needs to be configured with the GitHub repository associated with the site.

```javascript
// settings for ShareThis
const shareThis = window.ShareThis;
// uncomment to load a twitter sharer
// const twitterSharer = window.ShareThisViaTwitter;

// set this to your
const githubRepo = "jrnold/bookdown-github-issues";
// optionally add a github label to use
const githubIssueLabel = null;
const githubSharer = new GitHubIssueSharer(githubRepo, label = githubIssueLabel);

const selectionShare = shareThis({
    // sharers: [ githubSharer, twitterSharer ]
    sharers: [ githubSharer ]
});
selectionShare.init();
```

Add this line to `_output.yml`:
```yaml
bookdown::gitbook:
  # ...
  includes:
    in_header:
    - "includes/share-this.html"
```
